//
//  AddressModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class AddressModel: Model {
    public var addressToken: String = ""
    public var name: String = ""
    public var street: String = ""
    public var street2: String = ""
    public var city: String = ""
    public var state: String = ""
    public var postalCode: String = ""

    public var user: UserModel?

    public override func mapping(map: Map) {
        addressToken <- map["addressToken"]
        name <- map["name"]
        street <- map["street"]
        street2 <- map["street2"]
        city <- map["city"]
        state <- map["state"]
        postalCode <- map["postalCode"]
        user <- map["user"]
    }
}
