//
//  AutoPhotoModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class AutoPhotoModel: Model {
    public var autoPhotoToken: String = ""
    public var caption: String = ""
    public var photo_url: String = ""

    public var auto: AutoModel?

    public override func mapping(map: Map) {
        autoPhotoToken <- map["autoPhotoToken"]
        caption <- map["caption"]
        photo_url <- map["photo_url"]
        auto <- map["auto"]
    }
}
