//
//  BidModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class BidModel: Model {
    public var latitude: CGFloat = 0
    public var longitude: CGFloat = 0
    public var bearing: CGFloat = 0
    public var eta: Int = 0
    public var pickedUp: Bool = false

    public var auto: AutoModel?
    public var driver: UserModel?

    public override func mapping(map: Map) {
        latitude <- map["latitude"]
        longitude <- map["longitude"]
        bearing <- map["bearing"]
        eta <- map["eta"]
        pickedUp <- map["pickedUp"]
        auto <- map["auto"]
        driver <- map["driver"]
    }
}
