//
//  DeliveryModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class DeliveryModel: Model {
    public var delivAreaId: Int = 0
    public var approved: Bool = false
    public var approvedDate: Date? = Date(timeIntervalSince1970: 1)
    public var rejected: Bool = false
    public var rejectedDate: Date? = Date(timeIntervalSince1970: 1)
    public var rejectedReason: String = ""
    public var delivAgreement: Bool = false
    public var delivAgreementDate: Date? = Date(timeIntervalSince1970: 1)
    public var otherDeliv: Bool = false
    public var photo_url: String = ""
    public var approved_at: Date = Date(timeIntervalSince1970: 1)
    public var rejected_at: Date = Date(timeIntervalSince1970: 1)
    public var agreement_at: Date = Date(timeIntervalSince1970: 1)
    public var active_at: Date = Date(timeIntervalSince1970: 1)
    public var created_at: Date = Date(timeIntervalSince1970: 1)
    public var submitted: Bool = false
    public var deliv_status: String = ""

    public var area: AreaModel?
    public var user: UserModel?

    public override func mapping(map: Map) {
        delivAreaId <- map["delivAreaId"]
        approved <- map["approved"]
        approvedDate <- map["approvedDate"]
        rejected <- map["rejected"]
        rejectedDate <- map["rejectedDate"]
        rejectedReason <- map["rejectedReason"]
        delivAgreement <- map["delivAgreement"]
        delivAgreementDate <- map["delivAgreementDate"]
        otherDeliv <- map["otherDeliv"]
        photo_url <- map["photo_url"]
        approved_at <- (map["approved_at"], DateTransform())
        rejected_at <- (map["rejected_at"], DateTransform())
        agreement_at <- (map["agreement_at"], DateTransform())
        active_at <- (map["active_at"], DateTransform())
        created_at <- (map["created_at"], DateTransform())
        submitted <- map["submitted"]
        deliv_status <- map["deliv_status"]
        area <- map["area"]
        user <- map["user"]
    }
}
