//
//  DriverModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class DriverModel: Model {
    public var driverAreaId: Int = 0
    public var licenseState: String = ""
    public var licenseNum: String = ""
    public var licenseExp: Date? = Date(timeIntervalSince1970: 1)
    public var license1yr: Bool = false
    public var backDate: Date? = Date(timeIntervalSince1970: 1)
    public var approved: Bool = false
    public var approvedDate: Date? = Date(timeIntervalSince1970: 1)
    public var rejected: Bool = false
    public var rejectedDate: Date? = Date(timeIntervalSince1970: 1)
    public var rejectedReason: String = ""
    public var driverAgreement: Bool = false
    public var driverAgreementDate: Date? = Date(timeIntervalSince1970: 1)
    public var otherDriver: Bool = false
    public var photo_url: String = ""
    public var needs_license: Bool = false
    public var license_url: String = ""
    public var license_back_url: String = ""
    public var license_exp_at: Date = Date(timeIntervalSince1970: 1)
    public var approved_at: Date = Date(timeIntervalSince1970: 1)
    public var rejected_at: Date = Date(timeIntervalSince1970: 1)
    public var agreement_at: Date = Date(timeIntervalSince1970: 1)
    public var active_at: Date = Date(timeIntervalSince1970: 1)
    public var created_at: Date = Date(timeIntervalSince1970: 1)
    public var submitted: Bool = false
    public var launch_at: Int = 0
    public var driver_status: String = ""
    public var driver_message: String = ""
    public var camelotStatus: String = ""
    public var camelot_status_text: String = ""

    public var area: AreaModel?
    public var user: UserModel?

    public override func mapping(map: Map) {
        driverAreaId <- map["driverAreaId"]
        licenseState <- map["licenseState"]
        licenseNum <- map["licenseNum"]
        licenseExp <- (map["licenseExp"], PickAPIDateTransform())
        license1yr <- map["license1yr"]
        backDate <- map["backDate"]
        approved <- map["approved"]
        approvedDate <- map["approvedDate"]
        rejected <- map["rejected"]
        rejectedDate <- map["rejectedDate"]
        rejectedReason <- map["rejectedReason"]
        driverAgreement <- map["driverAgreement"]
        driverAgreementDate <- map["driverAgreementDate"]
        otherDriver <- map["otherDriver"]
        photo_url <- map["photo_url"]
        needs_license <- map["needs_license"]
        license_url <- map["license_url"]
        license_back_url <- map["license_back_url"]
        license_exp_at <- (map["license_exp_at"], DateTransform())
        approved_at <- (map["approved_at"], DateTransform())
        rejected_at <- (map["rejected_at"], DateTransform())
        agreement_at <- (map["agreement_at"], DateTransform())
        active_at <- (map["active_at"], DateTransform())
        created_at <- (map["created_at"], DateTransform())
        submitted <- map["submitted"]
        launch_at <- map["launch_at"]
        driver_status <- map["driver_status"]
        driver_message <- map["driver_message"]
        area <- map["area"]
        user <- map["user"]
        camelotStatus <- map["camelotStatus"]
        camelot_status_text <- map["camelot_status_text"]
    }
}
