//
//  DriverLocationModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class DriverLocationModel: Model {
    public var driverLocationToken: String = ""
    public var status: String = ""
    public var latitude: CGFloat = 0
    public var longitude: CGFloat = 0
    public var speed: CGFloat = 0
    public var course: CGFloat = 0
    public var updateDate: Date? = Date(timeIntervalSince1970: 1)

    public var user: UserModel?

    public override func mapping(map: Map) {
        driverLocationToken <- map["driverLocationToken"]
        status <- map["status"]
        latitude <- map["latitude"]
        longitude <- map["longitude"]
        speed <- map["speed"]
        course <- map["course"]
        updateDate <- map["updateDate"]
        user <- map["user"]
    }
}
