//
//  FavoriteModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class FavoriteModel: Model {
    public var createDate: Date? = Date(timeIntervalSince1970: 1)

    public var user: UserModel?
    public var savedUser: UserModel?

    public override func mapping(map: Map) {
        createDate <- map["createDate"]
        user <- map["user"]
        savedUser <- map["savedUser"]
    }
}
