//
//  LicenseModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class LicenseModel: Model {
    public var firstName: String = ""
    public var middleName: String = ""
    public var lastName: String = ""
    public var licenseState: String = ""
    public var licenseNum: String = ""
    public var licenseExp: Date? = Date(timeIntervalSince1970: 1)
    public var license1yr: Bool = false
    public var backDate: Date? = Date(timeIntervalSince1970: 1)
    public var license_url: String = ""
    public var license_back_url: String = ""
    public var license_exp_at: Date = Date(timeIntervalSince1970: 1)
    public var needs_license: Bool = false

    public var user: UserModel?

    public override func mapping(map: Map) {
        firstName <- map["firstName"]
        middleName <- map["middleName"]
        lastName <- map["lastName"]
        licenseState <- map["licenseState"]
        licenseNum <- map["licenseNum"]
        licenseExp <- (map["licenseExp"], PickAPIDateTransform())
        license1yr <- map["license1yr"]
        backDate <- map["backDate"]
        license_url <- map["license_url"]
        license_back_url <- map["license_back_url"]
        license_exp_at <- (map["license_exp_at"], DateTransform())
        needs_license <- map["needs_license"]
        user <- map["user"]
    }
}
