//
//  LoginHistoryModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class LoginHistoryModel: Model {
    public var ipAddress: String = ""
    public var agent: String = ""
    public var createDate: Date? = Date(timeIntervalSince1970: 1)

    public var user: UserModel?

    public override func mapping(map: Map) {
        ipAddress <- map["ipAddress"]
        agent <- map["agent"]
        createDate <- map["createDate"]
        user <- map["user"]
    }
}
