//
//  NetworkModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class NetworkModel: Model {
    public var repAreaId: Int = 0
    public var nickname: String = ""
    public var repAgreement: Bool = false
    public var photo_url: String = ""
    public var repAgreementDate: Date? = Date(timeIntervalSince1970: 1)

    public var user: UserModel?
    public var area: AreaModel?

    public override func mapping(map: Map) {
        repAreaId <- map["repAreaId"]
        nickname <- map["nickname"]
        repAgreement <- map["repAgreement"]
        photo_url <- map["photo_url"]
        repAgreementDate <- map["repAgreementDate"]
        user <- map["user"]
        area <- map["area"]
    }
}
