//
//  NotificationModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class NotificationModel: Model {
    public var notificationToken: String = ""
    public var message: String = ""
    public var contentUri: String? = ""
    public var read_at: Date? = Date(timeIntervalSince1970: 1)
    public var created_at: Date? = Date(timeIntervalSince1970: 1)

    public var user: UserModel?

    public override func mapping(map: Map) {
        notificationToken <- map["notificationToken"]
        message <- map["message"]
        contentUri <- map["contentUri"]
        read_at <- (map["read_at"], DateTransform())
        created_at <- (map["created_at"], DateTransform())
        user <- map["user"]
    }
}
