//
//  PhotoModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class PhotoModel: Model {
    public var photoToken: String = ""
    public var caption: String = ""
    public var sortOrder: Int = 0

    public override func mapping(map: Map) {
        photoToken <- map["photoToken"]
        caption <- map["caption"]
        sortOrder <- map["sortOrder"]
    }
}
