//
//  RefundModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class RefundModel: Model {
    public var refundToken: String = ""
    public var amount: CGFloat = 0
    public var completed: Bool = false
    public var createDate: Date? = Date(timeIntervalSince1970: 1)
    public var updateDate: Date? = Date(timeIntervalSince1970: 1)

    public var ride: RideModel?

    public override func mapping(map: Map) {
        refundToken <- map["refundToken"]
        amount <- map["amount"]
        completed <- map["completed"]
        createDate <- map["createDate"]
        updateDate <- map["updateDate"]
        ride <- map["ride"]
    }
}
