//
//  RequestModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class RequestModel: Model {
    public var requestToken: String = ""
    public var accepted: Bool = false
    public var createDate: Date? = Date(timeIntervalSince1970: 1)
    public var updateDate: Date? = Date(timeIntervalSince1970: 1)
    public var canceled: Bool = false

    public var ride: RideModel?
    public var user: UserModel?

    public override func mapping(map: Map) {
        requestToken <- map["requestToken"]
        accepted <- map["accepted"]
        createDate <- map["createDate"]
        updateDate <- map["updateDate"]
        canceled <- map["canceled"]
        ride <- map["ride"]
        user <- map["user"]
    }
}
