//
//  RideLocationModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class RideLocationModel: Model {
    public var latitude: CGFloat = 0
    public var longitude: CGFloat = 0
    public var speed: CGFloat = 0
    public var course: CGFloat = 0
    public var createDate: Date? = Date(timeIntervalSince1970: 1)

    public var ride: RideModel?
    public var user: UserModel?

    public override func mapping(map: Map) {
        latitude <- map["latitude"]
        longitude <- map["longitude"]
        speed <- map["speed"]
        course <- map["course"]
        createDate <- map["createDate"]
        ride <- map["ride"]
        user <- map["user"]
    }
}
