//
//  RideModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class RideModel: Model {
    public var rideToken: String = ""
    public var rideType: String = ""
    public var started_at: Date? = Date(timeIntervalSince1970: 1)
    public var startLat: CGFloat = 0
    public var startLong: CGFloat = 0
    public var startName: String = ""
    public var stopLat: CGFloat = 0
    public var stopLong: CGFloat = 0
    public var stopName: String = ""
    public var ended_at: Date? = Date(timeIntervalSince1970: 1)
    public var endLat: CGFloat = 0
    public var endLong: CGFloat = 0
    public var endName: String = ""
    public var startAmount: CGFloat = 0
    public var endAmount: CGFloat = 0
    public var tipAmount: CGFloat = 0
    public var waitMinutes: Int = 0
    public var status: String = ""
    public var created_at: Date? = Date(timeIntervalSince1970: 1)
    public var updated_at: Date? = Date(timeIntervalSince1970: 1)
    public var canceled: Bool = false
    public var cancelFee: CGFloat = 0

    public var auto: AutoModel?
    public var price: PriceModel?
    public var user: UserModel?
    public var driver: UserModel?
    public var bids: [BidModel]?
    public var photos: [PhotoModel]?
    public var refunds: [RefundModel]?
    public var requests: [RequestModel]?
    public var ride_locations: [RideLocationModel]?
    public var ride_payments: [RidePaymentModel]?
    public var ride_waits: [RideWaitModel]?
    public var transactions: [TransactionModel]?
    public var user_ratings: [UserRatingModel]?

    public override func mapping(map: Map) {
        rideToken <- map["rideToken"]
        rideType <- map["rideType"]
        started_at <- (map["started_at"], DateTransform())
        startLat <- map["startLat"]
        startLong <- map["startLong"]
        startName <- map["startName"]
        stopLat <- map["stopLat"]
        stopLong <- map["stopLong"]
        stopName <- map["stopName"]
        ended_at <- (map["ended_at"], DateTransform())
        endLat <- map["endLat"]
        endLong <- map["endLong"]
        endName <- map["endName"]
        startAmount <- map["startAmount"]
        endAmount <- map["endAmount"]
        tipAmount <- map["tipAmount"]
        waitMinutes <- map["waitMinutes"]
        status <- map["status"]
        created_at <- (map["created_at"], DateTransform())
        updated_at <- (map["updated_at"], DateTransform())
        canceled <- map["canceled"]
        cancelFee <- map["cancelFee"]
        auto <- map["auto"]
        price <- map["price"]
        user <- map["user"]
        driver <- map["driver"]
        bids <- map["bids"]
        photos <- map["photos"]
        refunds <- map["refunds"]
        requests <- map["requests"]
        ride_locations <- map["ride_locations"]
        ride_payments <- map["ride_payments"]
        ride_waits <- map["ride_waits"]
        transactions <- map["transactions"]
        user_ratings <- map["user_ratings"]
    }
}
