//
//  RideDataModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 09/23/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class RideDataModel: Model {
    public var routeData: [String: Any]?
    public var prices: [PriceModel]?
    public var priceToken: String = ""
    public var rideType: String = ""
    public var pickupPlace: PlaceModel?
    public var destination1: PlaceModel?
    public var destination2: PlaceModel?
    public var startAmount: CGFloat = 0

    public override func mapping(map: Map) {
        routeData <- map["routeData"]
        prices <- map["prices"]
        priceToken <- map["priceToken"]
        rideType <- map["rideType"]
        pickupPlace <- map["pickupPlace"]
        destination1 <- map["destination1"]
        destination2 <- map["destination2"]
    }
}
