//
//  ThreadModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class ThreadModel: Model {
    public var threadToken: String = ""

    public var messages: [MessageModel]?
    public var thread_users: [ThreadUserModel]?

    public override func mapping(map: Map) {
        threadToken <- map["threadToken"]
        messages <- map["messages"]
        thread_users <- map["thread_users"]
    }
}
