//
//  TransactionModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class TransactionModel: Model {
    public var transactionToken: String = ""
    public var amount: CGFloat = 0
    public var completed: Bool = false
    public var releaseDate: Date? = Date(timeIntervalSince1970: 1)
    public var createDate: Date? = Date(timeIntervalSince1970: 1)
    public var updateDate: Date? = Date(timeIntervalSince1970: 1)

    public var ride: RideModel?
    public var ride_payments: [RidePaymentModel]?

    public override func mapping(map: Map) {
        transactionToken <- map["transactionToken"]
        amount <- map["amount"]
        completed <- map["completed"]
        releaseDate <- map["releaseDate"]
        createDate <- map["createDate"]
        updateDate <- map["updateDate"]
        ride <- map["ride"]
        ride_payments <- map["ride_payments"]
    }
}
