//
//  UserRatingModel.swift
//  PickSDK
//
//  This code was generated by MakeSwift.php on 07/30/18, DO NOT EDIT.
//  Changes to this file will be lost if the code is regenerated.
//
//  Copyright © 2018 Pick Ride Network, Inc. All rights reserved.
//

import UIKit
import ObjectMapper

public class UserRatingModel: Model {
    public var userRatingToken: String = ""
    public var rate: Int = 0
    public var comment: String = ""
    public var ago: String = ""

    public var ride: RideModel?

    public override func mapping(map: Map) {
        userRatingToken <- map["userRatingToken"]
        rate <- map["rate"]
        comment <- map["comment"]
        ago <- map["ago"]
        ride <- map["ride"]
    }
}
